machine:
  node:
    version:
version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:latest
      - image: mongo:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install npm@5.3.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: 'sudo npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: 'sudo npm test'
